name: power
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_database: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#1f1f1f"
  image: "assets/logo.png"